# Create .do/app.yaml to force Docker
mkdir -p .do
cat > .do/app.yaml << 'EOF'
name: your-rails-app
services:
- name: web
  source_dir: /
  dockerfile_path: Dockerfile
  github:
    repo: alexinLead/secure_data_storage
    branch: main
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: RAILS_ENV
    value: production
  - key: DB_HOST
    value: aws-0-eu-north-1.pooler.supabase.com
  - key: DB_USERNAME
    value: postgres.jynfbdraigjscjlnswgf
  - key: DB_PASSWORD
    value: "@Thebestboy10"
  - key: DB_NAME
    value: postgres
  - key: DB_PORT
    value: "6543"
  - key: SECRET_KEY_BASE
    value: ff4259881221b56315e6fc566615f4598768997b6b4a41359b7ae610222f9f8383915c44117262351ce77c482155a93fe7d734596fde38a6c108d91a7aaf3158
EOF

git add .do/app.yaml Dockerfile
git commit -m "Force Docker build instead of buildpack"
git push alexinLead main