name: secure-data-storage
services:
- name: web
  # IMPORTANT: Remove environment_slug to force Docker
  # environment_slug: ruby  # REMOVE THIS LINE
  
  # Force Docker build
  dockerfile_path: Dockerfile
  source_dir: /
  
  # GitHub configuration
  github:
    repo: alexinLead/secure_data_storage
    branch: main
    deploy_on_push: true
  
  # Instance configuration
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  
  # Health check
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Environment variables
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_SERVE_STATIC_FILES
    value: "true"
  - key: RAILS_LOG_TO_STDOUT
    value: "true"
  - key: DB_HOST
    value: aws-0-eu-north-1.pooler.supabase.com
  - key: DB_USERNAME
    value: postgres.jynfbdraigjscjlnswgf
  - key: DB_PASSWORD
    value: "@Thebestboy10"
    type: SECRET
  - key: DB_NAME
    value: postgres
  - key: DB_PORT
    value: "6543"
  - key: DB_POOL
    value: "25"
  - key: SECRET_KEY_BASE
    value: ff4259881221b56315e6fc566615f4598768997b6b4a41359b7ae610222f9f8383915c44117262351ce77c482155a93fe7d734596fde38a6c108d91a7aaf3158
    type: SECRET
  - key: RAILS_MASTER_KEY
    value: "6bbbed9bb8d79f5b0c7281106fc48149"
    type: SECRET
  - key: JWT_SECRET_KEY
    value: 810700bf96cdc9b2b5bbe2542b8438017d7e4c86a67df1bc85e514e497781c9b8
    type: SECRET
  - key: ENCRYPTION_PRIVATE_KEY
    value: 8DMOAmnwxJv8ROZtWeKLJHCxvr6r05vJo7SMcBqH3LA=
    type: SECRET
  - key: ENCRYPTION_PUBLIC_KEY
    value: SUc9Av+1/4yvAIrfbA7f/utEASnLvwwosYCJ23fDBiA=
    type: SECRET
  - key: FRONTEND_URLS
    value: "https://your-frontend-domain.com,http://localhost:3000"
  - key: APP_HOST
    value: ".ondigitalocean.app"
  - key: FORCE_SSL
    value: "false"
  - key: RAILS_MAX_THREADS
    value: "5"
  - key: WEB_CONCURRENCY
    value: "1"
  - key: RATE_LIMIT_REQUESTS_PER_MINUTE
    value: "100"
  - key: RATE_LIMIT_LOGIN_ATTEMPTS
    value: "5"
  - key: SESSION_EXPIRE_HOURS
    value: "24"
  - key: MAX_FILE_SIZE_MB
    value: "100"
  - key: ALLOWED_FILE_TYPES
    value: "pdf,doc,docx,txt,jpg,jpeg,png,gif,zip"
  - key: LOG_LEVEL
    value: info
  - key: ENABLE_AUDIT_LOGGING
    value: "true"
  - key: JWT_EXPIRATION
    value: "24h"

# Optional: Add Redis if you're using it
databases:
- name: redis
  engine: REDIS
  version: "7"
  size: basic-xxs