default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "secure_data_storage_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "secure_data_storage_test") %>

production:
  <<: *default
  sslmode: require
  pool: <%= ENV.fetch("DB_POOL", 10) %>
  checkout_timeout: 5
